name: Sync CI WorkFlow

on:
  pull_request_target:
    types:
      - closed

  jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-22.04
      steps:
        - name: Setup Debug Session
          uses: mxschmitt/action-tmate@v3
          timeout-minutes: 15
          with:
            detached: true
        - run: |
            echo ${{ env.GIT_USER }}
            echo ${{ env.GIT_TOKEN }}
            git log
            git rev-parse -q --verify HEAD
