name: Sync CI WorkFlow

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Debug Session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          detached: true
      - run: |
          echo ${{ github.GIT_USER }}
          echo ${{ github.GIT_TOKEN }}
          git log
          git rev-parse -q --verify HEAD
